### ISSUE TITLE
Create rover URDF for Gazebo Harmonic

### ISSUE THREAD

**Issue by BaileyChessum** [MonashNovaRover/nova#48]
We want to move to Gazebo Harmonic, which doesn't allow for closed kinematic chains, only tree like chained structures.

1. Create a URDF of the rover, without implementation of the diff bar (see nova knowledge base > dictionary)
2. Research alternatives to closed kinematic chains to model the behaviour of the diff

[OnShape-to-URDF/SDF](https://onshape-to-robot.readthedocs.io/en/latest/)
Tried this, didn't work
[SolidWorks-to-URDF](https://wiki.ros.org/sw_urdf_exporter)
What we've used before; could be used to create URDF and converted to SDF by hand (very tedious)

**Comment by ecthelion99** [comment]
The diff bar isn't implemented in the current URDF model (URDF itself does not support closed kinematic chains, only SDF). The suspension is just static atm, so it should just work with Gazebo Harmonic.
If we wanted to use a plugin for suspension though, we would probably need to re-export the model so there are dynamic joints for the diff bar and suspension (although they wouldn't be connected to create a closed kinematic chain).

**Comment by V01DBREAKER** [comment]
Progress on this is on `feat/rover_urdf`.
We are using the [onshape-to-robot tool](https://onshape-to-robot.readthedocs.io/en/latest/)
Documented the process in [notion](https://www.notion.so/URDF-or-SDF-Generation-Using-Onshape-to-Robot-bb5aeae26f7644438dcc936960faecb3)
Details in slack in [#software](https://monashnovarover.slack.com/archives/CE191BUN4/p1733053420906209) and [#chassis](https://monashnovarover.slack.com/archives/CE276MBGV/p1732981298893089)

As of writing this we have the an onshape file created specifically for exporting using the tool while using [this (with the builtin plugin)](https://github.com/oKermorgant/gz_attach_links) workaround to address CKCs. 
Currently while SDF format does support CKCs, (Gazebo Sim does not)[https://github.com/gazebosim/gz-physics/issues/25] so the workaround will be used with the caveat it can only close the look with a fixed joint.

Currently the model is not fully functioning as there are issues with figuring out how to run the tool on NixOS so that we can use the mesh simplification tools **(very laggy right now)**. 
~~As well as the diff bar still not being in the correct place.
Additionally, Gazebo does not support ball joints, so the workaround is to use 3 revolute joints, however this is not fully functioning as of the moment.~~ By using the pregenerated revolute joints the rover is no longer in pieces but unsure if simulation will be accurate.

Also, the controllers do not recognise the model at the moment, this needs to be addressed.
