### ISSUE TITLE
add gazebo depth camera sensor plugin

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/nova#67]
**CONTEXT**
With the change to Gazebo Harmonic, the Gazebo Classic plugins have broke and no longer work, so they need to be replaced with corresponding Gazebo Harmonic plugins.
See #gazebo-harmonic on Slack for latest updates.

**TODO**
- Research depth camera sensor plugin
- Integrate plugin into gazebo
- Integrate plugin with ROS
- Test plugin

**RESOURCES**
- [gz sensor plugin documentation](https://gazebosim.org/docs/latest/sensors/)
- [gz plugins](https://github.com/gazebosim/gz-sim/tree/gz-sim8/src/systems)
- [gz plugin tags](http://sdformat.org/spec?ver=1.10&elem=sensor)

**Comment by vic-bart** [comment]
See [here](https://app.slack.com/client/TDZHVSKAR/C07Q35T73V5) for most recent discussion.

The depth camera sensor plugin provides 2 relevant topics: a point cloud, and a depth image
- The point cloud currently cannot be displayed in rviz, due to the following error: `Could not transform from [Waratah/base_link/oak/stereo] to [map]`
- The depth image can be displayed, but appears to be corrupted due to using the R_FLOAT32 pixel format, which rviz [does not support](https://wiki.ros.org/rviz/DisplayTypes/Image)

The point cloud has the higher priority, since it's used by the Nav2 stack, but I think we can disregard the depth image for now? As far as I'm aware, it's currently only being used as an input to a point cloud generation package, which isn't needed since the plugin creates the point cloud directly.
Alternatively, we could do it so that the point cloud is disregarded, and the depth image is fed into that package to generate the point cloud, which is closer to what we actually do.

**Comment by dylan-gonzalez** [comment]
rviz cannot display depth images. Use [image_view ](https://docs.ros.org/en/rolling/p/image_pipeline/) instead

**Comment by vic-bart** [comment]
![Image](https://github.com/user-attachments/assets/70023a7b-cf69-44d2-9a30-6ee68f6a6b0b)
Looks like image-view can't work with this pixel format 😩 
The solutions we found:
- https://robotics.stackexchange.com/questions/50122/error-unable-to-convert-32fc1-image-to-bgr8-while-extracting-rbgd-data-fro
- https://robotics.stackexchange.com/questions/81641/conversion-from-32fc1-to-mono8-using-cv-bridge

We can make a node to republish the depth image in an rviz-friendly pixel format, but since the depth image is only used to generate a point cloud, and we already have that thanks to @V01DBREAKER, there's no reason to pursue that solution for now; I think we'll mark this as complete for now, and come back to this if we ever need the depth image from gazebo.

**Comment by vic-bart** [comment]
Done, see PR #121
